// The app's audio identity: two cues built on a rising perfect fourth
// (D4 → G4). See docs/audio-identity.md; the samples are generated by
// scripts/make-cues.py. Only these two moments make a sound — no taps, no saves.
import { createAudioPlayer, type AudioPlayer } from 'expo-audio';
import { Platform } from 'react-native';

import { applyAudioMode } from './audio-mode';
import type { CueVoice } from './cue-voice';
import { metronomeRunning } from './metronome';

// same motif in four timbres; the voice follows the primary instrument (#53)
const SESSION_COMPLETE: Record<CueVoice, number> = {
  mallet: require('../../assets/audio/cue-session-complete.wav'),
  pluck: require('../../assets/audio/cue-session-pluck.wav'),
  bow: require('../../assets/audio/cue-session-bow.wav'),
  perc: require('../../assets/audio/cue-session-perc.wav'),
};

const players: Partial<Record<CueVoice, AudioPlayer>> = {};
let lastPlay = 0;

/**
 * "Mallet resolve" — plays once when a session is saved. Silent when the
 * Sounds setting is off, while the metronome is running (never talk over the
 * click), or when the device is on silent: playsInSilentMode stays false, so
 * iOS mutes it for us rather than us second-guessing the ring switch.
 */
export function playSessionComplete(enabled: boolean, voice: CueVoice = 'mallet') {
  if (!enabled || Platform.OS === 'web' || metronomeRunning()) return;
  // ponytail: one cue per 3s. The review effect fired twice and doubled the
  // sound (#53); a window costs one comparison and survives whatever remount
  // caused it. Drop it if the caller ever needs two cues back to back.
  if (Date.now() - lastPlay < 3000) return;
  lastPlay = Date.now();
  try {
    applyAudioMode({ playsInSilentMode: false, shouldPlayInBackground: false, interruptionMode: 'mixWithOthers' });
    const p = (players[voice] ??= createAudioPlayer(SESSION_COMPLETE[voice]));
    // Rewind before the cue, not on a timer after it. Seeking does not resume
    // playback, but it does not stop it either: a rewind timed just past the
    // sample's 2.4s that landed while the cue was still sounding — which it did
    // whenever playback started late — sent it back to the top and you heard the
    // cue twice. A fresh player is already at 0, so the first cue is immediate.
    const rewound = p.currentTime > 0 ? p.seekTo(0).catch(() => {}) : Promise.resolve();
    rewound.then(() => p.play());
  } catch {
    // a cue is decoration — never let it break the review screen
  }
}
