import { StyleSheet } from 'react-native';

import { F, themed, type T } from '@/lib/theme';

/** Formats minutes as "1h 05m" or "45 min" through the translator. */
export const fmtTime = (min: number, t: (key: string, opts?: Record<string, unknown>) => string) =>
  min >= 60 ? t('progress.timeHM', { h: Math.floor(min / 60), m: min % 60 }) : t('progress.timeMin', { min });

export const stars = (v: number | null) => (v === null ? '—' : `★ ${v.toFixed(1)}`);

// One stylesheet for every section: they were one screen and share most of these.
export const useS = themed(({ C, fs, r }: T) => StyleSheet.create({
  bucketRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6, paddingVertical: 5, borderTopWidth: 1, borderTopColor: C.hairline },
  insightRow: { gap: 8, paddingVertical: 8, borderTopWidth: 1, borderTopColor: C.hairline },
  driftLegend: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 8 },
  driftItem: { flexDirection: 'row', alignItems: 'center', gap: 4, maxWidth: '48%' },
  bucketLabel: { flex: 1, fontFamily: F.bodyMed, fontSize: fs(13), color: C.ink },
  insight: { flex: 1, fontFamily: F.body, fontSize: fs(14), lineHeight: fs(20), color: C.ink },
  bucketStars: { fontFamily: F.bodySemi, fontSize: fs(12), minWidth: 42, textAlign: 'right' },
  // 2x2 rather than 4 across: a German label like INSGESAMT has no room in a
  // quarter of the card, and the reserved two-line label height keeps every
  // number on the same baseline whatever the language or font scale (#87).
  volumeRow: { flexDirection: 'row', flexWrap: 'wrap', rowGap: 14, columnGap: 12 },
  volumeCell: { flexBasis: '46%', flexGrow: 1, gap: 4 },
  volumeLabel: { lineHeight: fs(15), minHeight: fs(30) },
  volumeNum: { fontFamily: F.head, fontSize: fs(22), color: C.ink },
  volumeUnit: { fontFamily: F.bodyMed, fontSize: fs(12), color: C.sub },
  goalLabel: { fontFamily: F.bodyMed, fontSize: fs(14), color: C.ink },
  goalValue: { fontFamily: F.bodySemi, fontSize: fs(14), color: C.ink },
  goalTarget: { fontFamily: F.body, fontSize: fs(13), color: C.sub },
  goalNote: { fontFamily: F.body, fontSize: fs(12.5), color: C.sub },
  goalBadge: { fontFamily: F.bodySemi, fontSize: fs(12.5) },
  chart: { height: 110, flexDirection: 'row', gap: 10 },
  col: { flex: 1 },
  colLabel: { textAlign: 'center', fontFamily: F.bodySemi, fontSize: fs(10), color: C.tertiary, marginTop: 6 },
  monthHead: { alignItems: 'center', gap: 2, marginBottom: 14 },
  monthTitle: { fontFamily: F.bodySemi, fontSize: fs(15), color: C.ink, marginHorizontal: 6 },
  monthChev: { fontSize: fs(20), lineHeight: fs(22), paddingHorizontal: 4 },
  monthCount: { fontFamily: F.body, fontSize: fs(12.5), color: C.sub },
  dowRow: { flexDirection: 'row', gap: 5, marginBottom: 5 },
  dowText: { flex: 1, textAlign: 'center', fontFamily: F.bodySemi, fontSize: fs(10), color: C.tertiary },
  weekRow: { flexDirection: 'row', gap: 5, marginBottom: 5 },
  cell: { flex: 1, aspectRatio: 1, borderRadius: r(8), alignItems: 'center', justifyContent: 'center' },
  cellNum: { fontFamily: F.bodySemi, fontSize: fs(11.5) },
  viewRow: { marginTop: 4, marginBottom: 16 },
  legendRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 4, marginTop: 6 },
  legendSwatch: { width: 11, height: 11, borderRadius: r(3.5) },
  legendText: { fontFamily: F.body, fontSize: fs(10.5), color: C.tertiary, marginHorizontal: 2 },
  focusHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  chip: { height: 26, paddingHorizontal: 10, borderRadius: r(999), backgroundColor: C.track, alignItems: 'center', justifyContent: 'center' },
  chipSel: { backgroundColor: C.accentTint },
  chipText: { fontFamily: F.bodySemi, fontSize: fs(12), color: C.sub },
  skillRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  dayDetail: { marginTop: 16, paddingTop: 14, borderTopWidth: 1, borderTopColor: C.hairline },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between' },
  detailTitle: { fontFamily: F.body, fontSize: fs(14), color: C.sub },
  detailNote: { fontFamily: F.body, fontSize: fs(12.5), color: C.subStrong, fontStyle: 'italic', marginTop: 2 },
  detailEmpty: { fontFamily: F.body, fontSize: fs(13), color: C.subStrong, marginTop: 4 },
  skillName: { fontFamily: F.bodyMed, fontSize: fs(15), color: C.ink },
  skillLevel: { fontFamily: F.bodyMed, fontSize: fs(13), color: C.sub },
  emptyTitle: { fontFamily: F.head, fontSize: fs(16), color: C.ink },
  emptyText: { fontFamily: F.body, fontSize: fs(13.5), lineHeight: fs(20), color: C.sub, maxWidth: 250, textAlign: 'center' },
  tintBtn: { height: 42, paddingHorizontal: 18, borderRadius: r(12), backgroundColor: C.accentTint, alignItems: 'center', justifyContent: 'center', marginTop: 8 },
  tintBtnText: { fontFamily: F.bodySemi, fontSize: fs(14), color: C.accent },
  shareBtn: { width: 38, height: 38, borderRadius: r(19), backgroundColor: C.card, borderWidth: 1, borderColor: C.cardBorder, alignItems: 'center', justifyContent: 'center' },
  hint: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, paddingVertical: 10, borderRadius: r(12), backgroundColor: C.accentTint },
  hintText: { flex: 1, fontFamily: F.body, fontSize: fs(13), lineHeight: fs(18), color: C.accentDark },
  hintBtn: { fontFamily: F.bodySemi, fontSize: fs(13), color: C.accent },
  customise: { alignSelf: 'center', paddingVertical: 8, paddingHorizontal: 16 },
  customiseText: { fontFamily: F.bodySemi, fontSize: fs(14), color: C.accent },
  slidersBtn: { marginLeft: 'auto', width: 30, height: 30, borderRadius: r(15), backgroundColor: C.track, alignItems: 'center', justifyContent: 'center' },
  layoutRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, borderTopWidth: 1, borderTopColor: C.hairline },
  layoutLabel: { flex: 1, fontFamily: F.bodyMed, fontSize: fs(15), color: C.ink },
  moveRow: { paddingVertical: 10, borderTopWidth: 1, borderTopColor: C.hairline, gap: 4 },
  moveHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  moveMeta: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  moveChip: { height: 24, paddingHorizontal: 9, borderRadius: r(999), backgroundColor: C.track, alignItems: 'center', justifyContent: 'center' },
  moveChipText: { fontFamily: F.bodySemi, fontSize: fs(11.5), color: C.sub },
  moveStars: { fontFamily: F.bodySemi, fontSize: fs(12), color: C.accent },
  stageDots: { flexDirection: 'row', gap: 4 },
  stageDot: { width: 7, height: 7, borderRadius: r(3.5) },
  calNote: { fontFamily: F.body, fontSize: fs(12.5), lineHeight: fs(17), color: C.subStrong, fontStyle: 'italic', marginTop: 2 },
  pipeBar: { flexDirection: 'row', height: 14, borderRadius: r(7), overflow: 'hidden', backgroundColor: C.track },
  pipeLegend: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 },
  pipeItem: { flexDirection: 'row', alignItems: 'center', gap: 4, maxWidth: '48%' },
  sheetTitle: { fontFamily: F.head, fontSize: fs(20), color: C.ink, marginBottom: 8 },
}));
